apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vcc-eksctl
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
