apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vcc-eksctl-asg
  region: eu-west-2

managedNodeGroups:
  - name: ng-1-medium
    instanceType: t3.medium
    minSize: 1
    maxSize: 5
    desiredCapacity: 4
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        autoScaler: true
