apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pruebaeks
  region: us-east-1

managedNodeGroups:
  - name: pruebaeks
    instanceType: t3.small
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        autoScaler: true
