apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vcc-eksctl-fargate
  region: us-east-1


fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system

  - name: fp-dev
    selectors:
      - namespace: dev
        labels:
          env: dev
          checks: passed

